export const SET_INPUT_SEARCH = "SET_INPUT_SEARCH";

export const SET_CLICKED_POKEMON = "SET_CLICKED_POKEMON";

export const SET_MY_POKEMONS = "SET_MY_POKEMONS";

export const REMOVE_MY_POKEMON = "REMOVE_MY_POKEMON";

